import React from 'react';
import { Form, Nav } from 'react-bootstrap';

const TextArea = () => {

    const textAreaText: string = `As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.`

    return (
        <div>
            <div className='text-area-container'>
                <Nav variant="tabs" defaultActiveKey="/home">
                    <Nav.Item>
                        <Nav.Link href="/home">B</Nav.Link>
                    </Nav.Item>
                    <Nav.Item>
                        <Nav.Link eventKey="link-1">I</Nav.Link>
                    </Nav.Item>
                    <Nav.Item>
                        <Nav.Link eventKey="link-2">hyperlink</Nav.Link>
                    </Nav.Item>
                    <Nav.Item>
                        <Nav.Link eventKey="link-3">text cut</Nav.Link>
                    </Nav.Item>
                    <Nav.Item>
                        <Nav.Link eventKey="link-4">underline</Nav.Link>
                    </Nav.Item>
                    <Nav.Item>
                        <Nav.Link eventKey="link-5">underline</Nav.Link>
                    </Nav.Item>
                </Nav>

                <Form.Group className="py-3" controlId="exampleForm.ControlTextarea1">
                    <Form.Control as="textarea" rows={12} readOnly value={textAreaText} />
                </Form.Group>
            </div>
        </div>
    );
};

export default TextArea;